sot/cheta

Ska/engarchive/version.py

Added exception handling to the git call when getting the version for
use on Windows or other installations where the git executable is not
available.

Added exception handling to the git call

---

Ska/engarchive/file_defs.py
Ska/engarchive/version.py
transfer_stage.py
update_archive.py

The values in `file_defs.msid_root` and `file_defs.arch_root` were mostly being ignored in `update_archive.py` and `transfer_stage.py`, except for the location of temporary directories.  Instead `opt.data_root` was always defined and was always being used.  This makes `opt.data_root` the root dir in all cases, including temp dirs.

Remove file_defs.msid_root and arch_root from use in cron tools

---

update_archive.py

I don't know why this was ever working before.

Make truncate skip over not-found stat files

---

NOTES.add_content
Ska/engarchive/converters.py
Ska/engarchive/units.py
Ska/engarchive/version.py
update_archive.py

There is a bug in CXCDS L0 SIM decom wherein the 3LDRTMEK MSID is
incorrectly assigned (TSC and FA are reversed).  The calibration
of 3LDRTPOS from steps to mm is then also wrong because it uses
the FA conversion instead of TSC.
This function fixes 3LDRTMEK, then backs out the (incorrect) 3LDRTPOS
steps to mm conversion and re-does it correctly using the TSC conversion.
Note that 3LDRTMEK is (by virtue of the way mission operations run)
always "TSC".

Workaround for bug in DS L0 SIM decom of 3LDRTMEK and 3LDRTPOS

---

Ska/engarchive/fetch.py
Ska/engarchive/filetypes.dat
Ska/engarchive/tests/test_fetch.py
Ska/engarchive/version.py
update_archive.py

During dwell mode the following MSIDs are stepped on:
4PRT5BT
4RT585T
AFLCA3BI
AIRU1BT
CSITB5V
CUSOAOVN
ECNV3V
PLAED4ET
PR1TV01T
TCYLFMZM
TOXTSUPN
ES1P5CV
ES2P5CV
Because of an issue related to the placement of the dwell mode flag, these msids get a bad value at the beginning of a dwell mode, while the dwell mode values (DWELLnn) get a bad value at the end.

Add support for CTU dwell mode from TDB P013

---

Ska/engarchive/fetch.py
Ska/engarchive/tests/test_data_source.py
Ska/engarchive/tests/test_fetch.py
Ska/engarchive/tests/test_fetch_regr.py
Ska/engarchive/tests/test_units.py
Ska/engarchive/units.py
doc/fetch_tutorial.rst

This PR takes over from where #122 left off and supercedes it.
To do:

Support generalized sources for telemetry data (including MAUDE)

---

update_archive.py

Will install with no package version update.  Probably need some kind of independent versioning on update_archive.py or put it in the package.

Add CCDM15ENG to content types with 100 year max gap

---

Ska/engarchive/update_archive.py
Ska/engarchive/version.py

Using --state-codes-only was missing the `simdiag` and `sim_mrg` MSIDs that have custom STATE_CODES defined in fetch.py.
No need to make a release for now, this only affects one-time processing that was done related to #117.

State codes only fix

---

Ska/engarchive/check_integrity.py
Ska/engarchive/version.py

On GRETA there was a problem running check_integrity at the end of archive update.  This was due to `-data-root=/proj/sot/ska/data/eng_archive` while the fetch data root was `/proj/sot/ska/test/data/eng_archive`.  This might be related to the change in #117 in fetch of the internal basedir method, but I don't 100% understand how.
In any case the original code was done wrong and this fixes it.

Check integrity fix post #117

---

Ska/engarchive/update_archive.py
Ska/engarchive/version.py

Sometimes CXCDS processing puts gaps into some files that then block eng archive ingest.  For example after the day 66 NSM:
```
kadi$ grep -i warning daily.0/eng_archive.log 
2017-03-12 05:30:19,180 WARNING: found gap of 951.20 secs between archfiles simf605224159N001_a_diag0.fits.gz and simf605247152N001_a_diag0.fits.gz
2017-03-12 05:30:44,762 WARNING: found gap of 65.60 secs between archfiles simf605244134N001_coor0a.fits.gz and simf605247185N001_coor0a.fits.gz
2017-03-12 05:30:49,288 WARNING: found gap of 65.60 secs between archfiles simf605244134N001_tlm0a.fits.gz and simf605247185N001_tlm0a.fits.gz
2017-03-12 05:31:11,821 WARNING: found gap of 328.00 secs between archfiles ephinf605224257N001_hkp0.fits.gz and ephinf605247152N001_hkp0.fits.gz
```
This PR introduces a new command line …

Allow archive file gaps after a specified number of days

---

Ska/engarchive/converters.py
Ska/engarchive/version.py

Testing:
Manually read in an OBA4ENG FITS file with the PR-411 uplink transition date temporarily patched to be before the data in the FITS file.  Confirmed that the narrow and wide outputs were identical for OOBTHR02.  Then did same with transition date set to actual transition and saw that narrow and wide outputs differed as expected.
```
import pyfits
from Ska.engarchive.converters import *
hdus = pyfits.open('obcf599620705N001_4_eng0.fits.gz')
dat = hdus[1].data
hdus.close()
len(dat)
ndat = numpy_converter(dat)
ondat = obc4eng(ndat)
ondat.dtype.names
ondat['OOBTHR02'] - ondat['OOBTHR02_WIDE']
```
With this testing I'm planning to install shortly so that processing tomorrow morning will pick up the change.

Add OOBTHR 02-07 to wide MSIDs following PR-411

---

Ska/engarchive/fetch.py
Ska/engarchive/version.py

**Rationale**
From M. Baski: The 3.43 version of fetch in Ska.engarchive needs a minor fix to work via remote access (from Windows PCs).  Specifically, “import six” (or similar) needs to be added to the load_msid_names function (it reports “NameError: global name 'six' is not defined” since six has not been imported when this function runs on the server).  This will be needed for this large MATLAB release that is being tested.
**Interface impact**
None.
**Testing**
Passes unit tests for Ska and Ska3.  M. Baski did functional testing on Windows.
**Review**
Reviewed by M. Baski.
**Deployment**
This will be installed to HEAD Ska / Ska3 flight and GRETA Ska test / Ska3 flight and GRETA Ska dev after being approved.
**Backout**
The previous version can be re-installed with no trouble if a …

Fix missing import for remote use

---

Ska/engarchive/tests/test_data_source.py
Ska/engarchive/version.py

Update times in regression test corresponding to changes from MAUDE 0.7.4 to MAUDE 1.0.
These are tiny timestamp changes that 
Close #148

Update times on maude regression test for MAUDE 1.0

---

Ska/engarchive/fetch.py

Fixes #145.
I do not understand why the `bads` array is set with `WRITEABLE=False` for remote access, while the `vals` array fetched in the same context is not.  Nevertheless, this does fix the problem in my testing.
- Get onto OCC VPN
- Get into the `ska` environment in the `~/anaconda` installation (not my current default `~/anaconda3`).
- Do the following for functional test (this fails without the patch):
```
>>> import Ska.engarchive.remote_access
>>> Ska.engarchive.remote_access.access_remotely = True
>>> import Ska.engarchive.fetch_eng as fetch
...: 
Enter hostname (or IP) of Ska server (enter to cancel):131.142.---.---
Enter your login username [aldcroft]: <user>
Enter your password: <pass>
Establishing connection to 131.142.---.---...
>>> from Ska.engarchive.tests.test_fetch …
```

Set fetched bads array to be writeable, needed for remote access

---

Ska/engarchive/check_integrity.py
Ska/engarchive/converters.py
Ska/engarchive/derived/base.py
Ska/engarchive/transfer_stage.py
Ska/engarchive/update_archive.py
Ska/engarchive/version.py
add_derived.py

This updates the `update_archive.py` module so it runs on Py3 (Ska3).
Promotion plan:
Testing was done with `ska_testr` using the `eng-archive-fix` branch and no diffs from flight output were found. Relevant output of the `test_make_regr_long.sh` script is:
```
Bash-10:14:47> cd eng_archive
Bash-10:14:47> 
Bash-10:14:47> # Checkout test branch, either ENG_ARCHIVE_BRANCH env var or master.
Bash-10:14:47> # Google "bash parameter expansion" for this syntax.
Bash-10:14:47> git checkout ${ENG_ARCHIVE_BRANCH:-master}
Branch py3-update set up to track remote branch py3-update from origin.
Switched to a new branch 'py3-update'
Bash-10:14:47> 
Bash-10:14:47> mkdir data
Bash-10:14:47> 
Bash-10:14:47> CONTENTS="--content=acis2eng --content=acis3eng --content=acisdeahk --content=simcoor …
```

Make update_archive.py module py3-compatible

---

Ska/engarchive/fetch.py
Ska/engarchive/version.py

Fixes #150 
As a reminder, the appropriate ska_remote_access.json file needs to be in place.
```
(ska3) neptune$ ska_version
2018.12.18-f55b6df
(ska3) neptune$ export ENG_ARCHIVE=/proj/sot/ska/data/eng_archive
(ska3) neptune$ ipython
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: >>> import Ska.engarchive.remote_access
...: >>> Ska.engarchive.remote_access.access_remotely = True
...: >>> import Ska.engarchive.fetch_eng as fetch
...: 
Enter hostname (or IP) of Ska server (enter to cancel):131.142.xxx
Enter your login username [aldcroft]:SOT
Enter your password:
Establishing connection to 131.142.xxx...
fetch: using …
```

Fix remote data access for Ska3

---

Ska/engarchive/converters.py
Ska/engarchive/version.py

The data array values at this point in the code are bytestrings, not unicode so the equality test was failing.  The MSIDs 3LDRTMEK and 3LDRTPOS after around 2018:336 were incorrect.  This fix restores the correct functionality in this function which was introduced in #121.
Testing:
- Truncated a local copy of the archive from 2018:280.  The data reprocessing to catch up after the safe mode was done using this code and was also impacted.  See also #154.
- Updated the local copy using the new code.
- Confirmed expected values by comparing with MAUDE queries (notice the red entirely overlaps blue)
```
In [1]: impska
In [2]: dat = fetch.Msid('3ldrtpos', '2018:334', '2018:339')
In [3]: fetch.data_source.set('maude')
In [4]: datm = fetch.Msid('3ldrtpos', '2018:334', '2018:339')
In [5]: …
```

Fix SIM_MRG comparison bug introduced in Py3 transition

---

Ska/engarchive/fetch.py

This requires https://github.com/sot/pyyaks/pull/6 to be installed to function on Windows.
I suspect that Windows was broken for queries before 2000:001 but not sure.

Use os.pathsep instead of ':' for Windows compatibility

---

Ska/engarchive/update_archive.py

This makes it possible to truncate an archive that has only some MSIDs.  It does require `archfiles.db3` and `colnames.pickle` in every content dir, but not all content dirs need be defined.

Allow truncation of incomplete local archive

---

Ska/engarchive/tests/test_sync.py
Ska/engarchive/update_client_archive.py
Ska/engarchive/update_server_sync.py
Ska/engarchive/utils.py

This runs in a minute or two, so right now it is part of standard testing.
For the record, this has a few parts:
- Define a limited set of content types and MSIDs that cover cases like rarely sampled telemetry (CPE gyro data and SPE-B gyro data), Ephemeris (with heavily overlapping full-res data), and then all different data types.
- Make a hard-copy replica of required files in a local version of the full "flight" archive. 
- Use that hard-copy replica to generate from scratch the sync repository files.  Using the local version allows for generating sync files for only the MSIDs being tested instead of the hundreds of others in the content types.  This makes things much lighter and faster.
- Make a client archive consisting of "stub" versions of required files which consist of mostly …

End to end unit test of syncing

---

Ska/engarchive/tests/test_sync.py

Tests were not working for the "flight" archive sitting on an external disk.  This fixes it as long as symlinking is allowed by the OS.

Allow test device cross mount with symlink if supported

---

Ska/engarchive/fetch.py
Ska/engarchive/remote_access.py
Ska/engarchive/tests/test_data_source.py
Ska/engarchive/tests/test_remote_access.py
Ska/engarchive/tests/test_sync.py
Ska/engarchive/update_client_archive.py
Ska/engarchive/update_server_sync.py
doc/fetch_tutorial.rst

This does two somewhat independent things:
- Improve remote access control by allowing for a `SKA_ACCESS_REMOTELY` user environment variable to explicitly control whether the remote server is used.  Along the way the logic and implementation were refined as noted in the improved user documentation.
- Adds unit tests of remote access (to the extent possible) and describes manually-run tests.
- Fix some path issues in the sync mechanism that only showed up on a FOT Windows laptop.
Testing using an installed version of the package.  "Limited" unit tests done with:
```
>>> import Ska.engarchive
>>> Ska.engarchive.test('-k test_sync', '-s', '-v')
>>> Ska.engarchive.test('-k test_remote_access', '-v')
```
Testing status
Manual test:
- Nominal remote access on Windows:
No env vars set (SKA, …

Improve remote access and fix sync to work on FOT Windows

---

.gitignore
Ska/engarchive/tests/test_sync.py
Ska/engarchive/version.py

This also updates the version to 4.45.1 and does an unrelated update to .gitignore that makes life easier in my development.
See the note here for inspiration: https://docs.python.org/3.6/library/platform.html#platform.architecture
```
quango% pytest Ska/engarchive/tests/ -k sync -v
======================================= test session starts ========================================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /proj/sot/ska3/matlab32/bin/python
cachedir: .cache
rootdir: /data/baffin/tom/git/eng_archive, inifile:
plugins: arraydiff-0.2, doctestplus-0.1.3, openfiles-0.3.0, remotedata-0.3.0
collected 79 items                                                                                  
Ska/engarchive/tests/test_sync.py::test_sync[acis4eng] …
```

Skip sync tests on 32-bit platform (version 4.45.1)

---

Ska/engarchive/update_client_archive.py
Ska/engarchive/update_server_sync.py
Ska/engarchive/version.py

Key changes:
1.  Change flow so all available data updates are downloaded in one step, then concatenated into a single update, and then applied to the local files.  Previously it was doing all processing (fetch and apply) for each available daily update in sequence.  This was simpler but it turns out that most of the processing time is actually in updating the HDF5 files (largely independent of update size), not in downloading data.  So if you are syncing your archive after a month then this change makes the update nearly 30 times faster.
2. Add a context manager to prevent user hitting keyboard interrupt (ctrl-c) during critical file update operations where the archive can get corrupted.  This doesn't prevent other problems (force quit etc), but at least helps the common case.

More robust and faster sync

---

Ska/engarchive/update_client_archive.py
Ska/engarchive/version.py
setup.py
task_schedule_sync.cfg

This copies content from a remote server or separate directory (normally an external drive) with a full copy of the archive.  The MSIDs to copy are defined in a simple flat file, for example the following file named `msid_specs` (used in examples below):
```
aopcadmd
aacccd*
*/1wrat
**/3tscpos
```
Example usage.  In all cases you can provide a `--dry-run` option to avoid actually doing any copies.
```
$ mkdir test
$ python -m cheta.update_client_archive --add-msids-from-file=msid_specs \
--server-data-root=aldcroft@ccosmos --data-root=test [--dry-run]
$ python -m cheta.update_client_archive --add-msids-from-file=msid_specs \
--server-data-root=/proj/sot/ska/data/eng_archive --data-root=test
$ ipython
import os
os.environ['ENG_ARCHIVE'] = 'test'
from cheta import fetch …
```

Functionality to add content to local archive by MSID

---

Ska/engarchive/fetch.py

As noted in the cheta sync tutorial, using data on an external drive was not working.  This was due to an issue in `_split_path` from @mbaski years ago where it was always just dropping the drive from the path.  This PR uses `pathlib.Path` to do the heavy lifting and allows for a path that is different from the default drive `C:\\`.
Testing on Windows VM:
- Tested with remote access by setting the `SKA_ACCESS_REMOTELY` env var to `'True'` and confirmed expected behavior after connecting to `chimchim`.
- Tested using a USB drive with a subset of cheta data on `E:\\cheta`.

Fix _split_path to work for non-C: drives on Windows

---

Ska/engarchive/update_archive.py
Ska/engarchive/update_server_sync.py
Ska/engarchive/version.py

Fixes #184.
Along the way I noticed there is also an off-by-one in truncating the stats archive.  Normally not really a problem but again these rarely-sampled MSIDs can have a problem where you lose a record and then the lookback time is not far enough to get it the next time around.
- Regenerated sync files for AOSPASA2CV in pcad7eng covering 2019-09-20 to 2019-11-18 and confirmed that there is no longer a "misplaced row".
- Truncated pcad7eng (AOSPASA2CV only) at 2019-10-01 and confirmed that the last 5min record before then (which should be row 108206) is no longer dropped.
- Ran the same command after truncating and confirmed the expected behavior of saying that no rows are available to truncate.

Fix off by one errors in sync file generation and truncate

---

Ska/engarchive/update_server_sync.py

I ran into a problem with ccdm15eng data not syncing correctly.  This was due to my local copy missing one sync dir that had since been removed from the primary sync archive because it was older than 60 days.
Ccdm15eng is dwell-mode telemetry that (mostly) only shows up when we have a momentum dump, which as been quite infrequent of late.
Passes unit tests (including sync tests)
```
$  python -m cheta.update_server_sync --content=acis4eng --max-days=1.0 --max-sync-dirs=3 --date-start=2019:001 --date-stop=2019:004
$  python -m cheta.update_server_sync --content=acis4eng --max-days=1.0 --max-sync-dirs=3 --date-stop=2019:005
$  python -m cheta.update_server_sync --content=acis4eng --max-days=1.0 --max-sync-dirs=3 --date-stop=2019:005
$  python -m cheta.update_server_sync --content=acis4eng …
```

Allow a fixed number of sync dirs instead of removing by date

---

Ska/engarchive/derived/base.py
Ska/engarchive/derived/comps.py
Ska/engarchive/derived/mups_valve.py
Ska/engarchive/fetch.py
Ska/engarchive/tests/test_comps.py
Ska/engarchive/units.py
doc/fetch_tutorial.rst
doc/pseudo_msids.rst

This adds new functionality to allow for on-the-fly computed MSIDs.
It also adds new built-in computed MSIDs for MUPS valve temperatures.
To do:
- New unit tests.

Add code to support and test computed MSIDs

---

Ska/engarchive/fetch.py

The adds a title and y-label to the standard cheta `MSID.plot()` output.  Should have done this a long time ago!
- Made a plot for TEPHIN (with a unit), looks good
- Made a plot for AOPCADMD (no unit), looks good
- Made a plot for CMD_STATE_PITCH_32 (no unit), looks good

Add MSID title and unit y-label to plot

---

.github/workflows/flake8.yml
Ska/engarchive/update_archive.py

The task_schedule log checking is looking for warnings, but the code that indicated a telemetry gap was being allowed because 4 days have passed was being issued without WARNING.  This meant the alert email was missing that key information.
Along the way I decided that the null file overlap is no never actionable, so downgraded that to INFO.
This also does some flake8 updates.
No applicable unit tests.  Doing functional testing is not especially easy. Given the scope of changes just being updating the value of strings, it is not necessary.

Better warnings

---

Ska/engarchive/derived/comps.py
Ska/engarchive/derived/mups_valve.py
Ska/engarchive/tests/test_comps.py

This introduces an optional element of the computed cleaned MUPS value temperature MSIDs which allows specifying the MUPS model version. It now accepts an MSID like `pm1thv2t_clean_3.28` which would use release 3.28 of https://github.com/sot/chandra_models to get the model spec file. This is crucial for reproducible tests going forward. The default version is still from current master.
The tests were updated to pass with release 3.30. I spent some time trying to find a version of chandra_models for which the original tests would pass but failed. This is something of a mystery since tests were definitely passing at the time the original computed MSIDs PR was merged. Regardless, tests are passing now.
Related to fixing tests, one bit of non-numba-able code was moved out of a `@numba.jit()` …

Allow model version in MUPS clean computed MSID and fix tests

---

Ska/engarchive/tests/test_comps.py
Ska/engarchive/tests/test_fetch.py
Ska/engarchive/tests/test_intervals.py
pytest.ini

Changes to get tests passing on shiny. These are all related to using Chandra.Time 4.0.
- [N/A] Functional testing

Shiny tests

---

Ska/engarchive/remote_access.py

This is a latent issue that was breaking the ska_testr long test, and would have prevented adding a new derived parameter.
Now passes the ska_testr long test on HEAD.

Allow multiple paths in ENG_ARCHIVE

---

Ska/engarchive/fetch.py
Ska/engarchive/lazy.py

This removes the step of initializing the list of available MSIDs during the import of `cheta.fetch`. This step had previously kicked off the setup of the remote server in the case of remote access.
This script works on Windows and MacOS in this branch. On Window in `master`, it fails because the remote setup ends up re-importing the script and redoing the remote setup.
```
import os
print(f'Running imports with process id={os.getpid()}')
os.environ.pop('SKA', None)
os.environ.pop('ENG_ARCHIVE', None)
os.environ['SKA_ACCESS_REMOTELY'] = 'True'
from Ska.engarchive import fetch, remote_access  # noqa
def main():
print(f'  HERE main() with process id={os.getpid()}')
fetch.add_logging_handler()
assert remote_access.access_remotely is True
fetch.Msid('tephin', '2018:001', '2018:010')
if …
```

Lazy-load inital content and remote access setup

---

Ska/engarchive/derived/comps.py
Ska/engarchive/derived/mups_valve.py
Ska/engarchive/tests/test_comps.py

This takes advantage of the new xija_get_model_spec() function in xija to remove the dependency on GitHub for the MUPS valve computation. It also fixes the test fail on cheru which cannot see GitHub.
There was an oddity where the commit that was hardwired into the testing was orphaned somehow (maybe lost from a rebase?). That commit did not appear in a clone from GitHub.

Use get_xija_model_spec instead of GitHub for pftank2t model

---

Ska/engarchive/fetch.py

This improves the caching in fetch in two ways:
1. Use a timeout for the cache of the row start/stop interval for given content, tstart, tstop inputs.
1. Use a more robust cache key for caching the times arrays for a query. The previous key could lead to a failure if the archive was updated between subsequent queries.
The inspiration is an issue with the cheta archive where a persistent session was unable to see new updates in the data.
This requires https://github.com/sot/ska_helpers/pull/20.
The `fetch.py` code was patched to have a 10-second timeout instead of the actual 10-minute timeout. Then this code was run:
```
from cheta import fetch
import time
t0 = time.time()
def fetch_msid(msid, wait):
dt = time.time() - t0
print(f'dt={dt:.0f} {msid=} {wait=}')
fetch.Msid(msid, '2020:001', …
```

Better caching in fetch

---

.github/workflows/flake8.yml
Ska/engarchive/file_defs.py

Fix the last PEP8 holdout in cheta code. I used to think lining up entries was a good idea, but no more.
- [N/A] Functional testing

Fix file_defs.py for PEP8

---

Ska/engarchive/file_defs.py
Ska/engarchive/update_client_archive.py
Ska/engarchive/update_server_sync.py

Set sync index column order to match the alphabetical order that resulted in astropy 4.0.  In astropy 4.2 the column order when initializing from a list of dict is the order of keys in the first row. Since astropy 4.2 requires Python 3.7, which has dict ordered, this makes more sense than the previous behavior of just alphabetizing.
- [N/A] Functional testing
This showed up in unit test failures with astropy 4.2 in skare 2021.2 env on linux, so the unit tests passing are probably sufficient.
Fixes #216

Fix sync index column order to match order from astropy 4.0

---

Ska/engarchive/update_archive.py
Ska/engarchive/utils.py

Use https://github.com/sot/ska_helpers/pull/21 to hopefully make the daily archive updates more resilient to HEAD NetApp issues.
```
2021-02-08 04:03:57,089 Updating stats file /proj/sot/ska3/flight/data/eng_archive/data/acisdeahk/daily/TMP_FEP1_MONG.h5
2021-02-08 04:03:57,175   Adding 3 records
2021-02-08 04:03:57,211 Updating stats file /proj/sot/ska3/flight/data/eng_archive/data/acisdeahk/5min/TMP_FEP1_MONG.h5
Traceback (most recent call last):
File "/proj/sot/ska3/flight/bin/cheta_update_server_archive", line 33, in <module>
sys.exit(load_entry_point('Ska.engarchive==4.51.0', 'console_scripts', 'cheta_update_server_archive')())
File "/proj/sot/ska3/flight/lib/python3.8/site-packages/cheta/update_archive.py", line 1186, in main
main_loop()
File …
```

Retry tables open file

---

Ska/engarchive/derived/thermal.py

The heater zones within the Telescope Bus 5 and Bus 6 cannot be commanded if either of these busses are disabled, such as when the Telescope Bus 6 is disabled to turn off the stuck on Zone 50 heater. From what I can tell, the bilevel heater telemetry for these zones does not depend on bus state, but rather commanding from the OBC, so if a temperature were to drop below the heater set point within a zone in Bus 5 or Bus 6, the relevant bilevel MSID would likely falsely indicate the heater is ON.
This update uses the Telescope Bus 5 and Bus 6 state to correct any false Telescope Bus 5 or Bus 6 bilevel telemetry, including within Zone 50.
I completed some testing by redefining the DerivedParameterThermal and affected classes locally (in a notebook), and was able to confirm that the code …

Use Telescope Bus 5 and Bus 6 state to calculate relevant derived thermal parameters

---

Ska/engarchive/update_client_archive.py

When adding MSIDs to a cheta local archive where the content type already exists, it does not update the `colname.pkl` file, thus leaving the new MSIDs invisible to fetch.
Ran this on my Mac on an up-to-date local archive and confirmed:
- The `colnames.pkl` files were still copied even though they exist
- New debug logging appears
```
(ska3) ➜  eng_archive git:(fix-add-msids) python -m cheta.update_client_archive --add-msids=p015.txt --server-data-root=aldcroft@ccosmos.cfa.harvard.edu --dry-run --log-level=1
2021-03-25 06:45:06,948 Running cheta_update_client_archive version 4.52.1.dev1+gaf6a60d
2021-03-25 06:45:06,948   /Users/aldcroft/git/eng_archive/cheta/update_client_archive.py
2021-03-25 06:45:06,948 
2021-03-25 06:45:06,948 Updating client archive at …
```

Fix a problem adding MSIDs to existing content type

---

NOTES.fix_bad_ingest.rst
NOTES.gap_process

This documents the process I ended up following to fix up the `acisdeahk` problem from 2021:118.
- [N/A] Passes unit tests on MacOS, linux, Windows (at least one required)

New NOTES file for a bad ingest + gap process update

---

Ska/engarchive/derived/base.py

This PR makes tiny changes to remove uses of a few deprecated dtypes (https://github.com/sot/skare3/issues/753)
Fixes #

remove use of deprecated np.bool

---

Ska/engarchive/fetch.py
Ska/engarchive/tests/test_fetch.py

This fixes a problem when unpickling an `MSIDset` and adds tests for both that class and `MSID`.
- [n/a] Functional testing

Fix pickling for MSIDset and add tests

---

Ska/engarchive/tests/test_data_source.py

The following integration tests are currently failing:
```
FAILED Ska/engarchive/tests/test_data_source.py::test_maude_data_source - AssertionError: assert {'maude': {'f...0:00:04.900'}} == {'maude': {'f...0:00:04.900'}}
FAILED Ska/engarchive/tests/test_data_source.py::test_zero_length_fetch_maude - AssertionError: assert {'maude': {'f...nce': False}}} == {'maude': {'f...nce': False}}}
FAILED Ska/engarchive/tests/test_fetch.py::test_fetch_derived_param_aliases[sources0-DP_piTch_fss] - assert 0 > 0
FAILED Ska/engarchive/tests/test_fetch.py::test_fetch_derived_param_aliases[sources0-Calc_pitCH_fss] - assert 0 > 0
FAILED Ska/engarchive/tests/test_fetch.py::test_fetch_derived_param_aliases[sources1-DP_piTch_fss] - assert 0 > 0
FAILED …
```

Fix integration tests

---

Ska/engarchive/tests/test_comps.py

This fixes the failure below, which is due to a change in the number of "bad" samples after the underlying MUPS thermal model was changed in `chandra_models` master since the test was written. The original test was badly designed and susceptible to this failure.
```
_______________________________ test_mups_valve ________________________________
def test_mups_valve():
colnames = ['vals', 'times', 'bads', 'vals_raw',
'vals_nan', 'vals_corr', 'vals_model', 'source']
dat = fetch_eng.MSID('PM2THV1T_clean_6854df4d', '2020:001:12:00:00', '2020:010:12:00:00')
assert dat.unit == 'DEGF'
assert len(dat.vals) == 36661
...
dat = fetch_eng.Msid('pm1thv2t_clean', '2020:001:12:00:00', '2020:010:12:00:00')
>       assert len(dat.vals) == 36240  # Some bad values
E       assert 36639 == 36240
E …
```

Fix test failure from updated MUPS model

---

Ska/engarchive/derived/comps.py
Ska/engarchive/tests/test_comps.py
pytest.ini

This adds a convenience interface to allow getting `Quat` objects for spacecraft telemetry directly from the cheta archive.
This defines the following computed MSIDs based on the corresponding TDB MSIDs:
- `quat_aoattqt = AOATTQT[1-4]`
- `quat_aoatupq = AOATUPQ[1-3]`
- `quat_aocmdqt = AOCMDQT[1-3]`
- `quat_aotarqt = AOTARQT[1-3]`
None
Independent check of unit tests by [REVIEWER NAME]
No functional testing.

Add computed MSID to return Quat for quaternion MSID sets

---

Ska/engarchive/tests/test_fetch.py

This might finally fix the intermittent problems with derived param aliases:
- Getting no samples with the original dt=200 was due to the fact that PITCH_FSS is not defined out of the FSS field of view, beyond pitch > 135. So sometimes there really was no data.
- Changed to PITCH_CSS. This is basically always available.
- Reduced interval from 86400 to 2000: I think that 86400 was too long and this was actually sampling realtime when the CXC archive was within a day of current. 
- Notice that the final time is increasing during the tests, and indeed `CxoTime(7.71253565e+08).date` = '2022:161:13:04:55.816' was during a realtime comm pass.
```
=================================== FAILURES ===================================
___________ test_fetch_derived_param_aliases[sources1-DP_piTch_fss] …
```

Possibly fix derived param aliases test

---

Ska/engarchive/fetch.py
Ska/engarchive/tests/test_fetch.py

The `MSIDset.filter_bad()` method was previously trying to be too clever and doing correlated union-based filtering on MSIDs within each content type. This is strongly tied to the concept of content types in the `cxc` dataset, but with increasing use of MAUDE as the backend this idea is less applicable.
Although it is an API change that might have an impact, this PR is to change the default behavior of filtering bad data in a set to simply filter each MSID in the set individually.
A small tag-along here is ensuring that MAUDE-dependent tests in `test_fetch.py` are skipped if MAUDE is not available.
Fixes #234 
This changes the default behavior of `MSIDset.filter_bad()`, and therefore the default behavior of `Msidset()` which calls `filter_bad()`. This API change should not impact much …

Change `MSIDset.filter_bad()` to apply to individual MSIDs by default

---

Ska/engarchive/update_server_sync.py

This will trigger emails that notify the team about issues with maintaining the cheta sync archive.
No testing given the scope of changes, which are limited to updates to format strings in the code.

Add warning/error to update_server_sync messages

---

Ska/engarchive/tests/test_sync.py
Ska/engarchive/update_client_archive.py

Fixes #239 
None
Independent check of unit tests by [REVIEWER NAME]
```
$ python -m cheta.update_client_archive --add-msids=msid_specs --data-root=. \
--server-data-root=aldcroft@kadi.cfa.harvard.edu --dry-run
fetch: using ENG_ARCHIVE=/Users/aldcroft/git/eng_archive for archive path
2022-09-13 09:19:54,845 Running cheta_update_client_archive version 4.56.1.dev11+g8ed7a4c
2022-09-13 09:19:54,845   /Users/aldcroft/git/eng_archive/cheta/update_client_archive.py
2022-09-13 09:19:54,845 
2022-09-13 09:19:54,845 Updating client archive at /Users/aldcroft/git/eng_archive
2022-09-13 09:19:54,845 Reading available cheta archive MSIDs from https://icxc.cfa.harvard.edu/aspect/cheta/
2022-09-13 09:19:55,092 Reading cheta MSIDs list file https://icxc.cfa.harvard.edu/aspect/cheta/sync/msid_contents.pkl. …
```

Fix server data root regex for copying server files

---

Ska/engarchive/fetch.py
Ska/engarchive/tests/test_intervals.py
Ska/engarchive/utils.py
docs/fetch_tutorial.rst

The utility function `cheta.utils.logical_intervals()` has a poor choice of default with `complete_intervals=True`, with only myself to blame. This means that any `True` intervals that extend to the start or stop of interval are dropped. This behavior is good and necessary in certain situations (like kadi events where you don't want to store partial/incomplete events), but **most** of the time you expect to get all the intervals within the data.
This default setting cost me a couple hours debugging in https://github.com/sot/kadi/pull/261 finding an issue that depended oddly on the start / stop times.
This changes a default that may impact code. For the most part I would expect that this will fix latent bugs where the code is actually assuming `complete_intervals=False`, but we'll need to …

Change logical_intervals() default complete_intervals from True to False

---

Ska/engarchive/derived/base.py
Ska/engarchive/derived/comps.py
Ska/engarchive/derived/pcad.py
Ska/engarchive/fetch.py
Ska/engarchive/tests/test_comps.py
docs/fetch.rst
docs/fetch_tutorial.rst
docs/ipython_tutorial.rst
docs/plot.rst
docs/pseudo_msids.rst
docs/tutorial.rst
docs/utils.rst

This is a new computed MSID to return the Sun pitch angle or off-nominal roll angle which is valid in NPNT, NMAN, NSUN, and Safe Mode. This new computed MSID also works with `MAUDE` as the back-end telemetry server (unlike e.g.  `dp_pitch/roll`).
Current available MSIDs are limited in scope. For instance `dp_pitch` is only good for `NPNT` or `NMAN` when PCAD processing is maintaining `AOATTQT1-4` accurately. Querying `dp_pitch` in other modes will return a value that is wrong.
The logic is:
- Get logical intervals for the online flight program (OFP) state:
- CONLOFP == "NRML":
- AOPCADMD in ["NPNT", "NMAN"] => compute pitch/roll from AOATTQT1/2/3/4 and ephemeris
- AOPCADMD == "NSUN" => get pitch/roll from PITCH/ROLL_CSS derived params. These are also in MAUDE.
- CONLOFP == "SAFE":
- …

Computed MSID for pitch/off-nominal roll + data gap + docs fixes

---

cheta/update_server_sync.py

Daily cheta cron processing failed when updating the cheta sync archive. This is due to a missing `overwrite=True` arg in the astropy Table `write()` method. This was not seen in testing because the test only does one "update" into a fresh directory. This could be improved...
```
2023-03-29 04:49:05,151 Writing 1 row(s) to index file /proj/sot/ska3/flight/data/eng_archive/sync/acis2eng/index.ecsv
Traceback (most recent call last):
File "/proj/sot/ska3/flight/bin/cheta_update_server_sync", line 33, in <module>
sys.exit(load_entry_point('cheta==4.58.0', 'console_scripts', 'cheta_update_server_sync')())
File "/proj/sot/ska3/flight/lib/python3.10/site-packages/cheta/update_server_sync.py", line 135, in main
update_sync_repo(opt, logger, content)
File …
```

Add overwrite=True to cheta sync index table write statement

---

cheta/derived/comps.py
cheta/tests/test_comps.py
pyproject.toml
pytest.ini

This removes a limitation of the original implementation for the computed quaternion pseudo-MSIDs (https://sot.github.io/cheta/pseudo_msids.html#cheta.derived.comps.Comp_Quat)
None
Independent check of unit tests by Jean
No functional testing.

Enable use of MAUDE with computed quaternion pseudo-MSID

---

cheta/derived/comps.py
cheta/tests/test_comps.py
cheta/tests/test_intervals.py
cheta/tests/test_utils.py
cheta/units.py
cheta/utils.py

This is a hodge-podge of related improvements to utilities in cheta. The initial driver was a problem in `[aca] Kadi commands state validation: ALERT` on Apr 1 ending with:
```
File "/proj/sot/ska3/flight/lib/python3.10/site-packages/cheta/utils.py", line 334, in state_intervals
raise ValueError("Filtered data length must be at least 2")
ValueError: Filtered data length must be at least 2
```
Generally speaking the original implementation of `pitch_comp` and `roll_comp` was not robust. It depended on `get_ofp_states` in `kadi.utils` which was also not robust. So this turned into an effort to revisit this code and make it work under most circumstances. In particular dealing with short query intervals was a focus.
Since the code hinges on `state_intervals` and `logical_intervals`, those got …

Improve pitch/roll_comp, logical_intervals, state_intervals, get_ofp_states, get_telem_table

---

cheta/fetch.py

The docstring for the two `filter_bad_times` methods was misleading since it said the `table` parameter should be set with a `2-column table` when in fact it should be a list of strings.
None
No testing, this is just a doc string update.
Built documentation and confirmed no errors and that the doc strings look good.

Fix misleading doc string

---

.github/workflows/flake8.yml
cheta/derived/comps.py

Using MAUDE data just after a comm for the `pitch_comp` and `roll_comp` computed MSIDs was failing for a couple of reasons:
- There was a 1-sample (2.05 sec) CONLOFP state that caused a problem in `state_intervals`. This was fixed by specifying the `start` and `stop` times (enabled by #249).
- The chunk of time after the comm where ephemeris data are available but no quaternions was being marked as bad by the telemetry fetching code but that was being used in subsequent processing to just set the `pitch` or `roll` to 0.0. Instead the data points need to be removed entirely. The updated code does this now.
None
Independent check of unit tests by Jean
Using this branch I ran a fetch query for `pitch_comp` about one hour after BOT. The query started before the comm and ended at the current …

Fix problems that came up in `pitch/roll-comp` when using real-time data

---

cheta/task_schedule.cfg

The HDF5 retry errors should not generate an alert email.
None
The `watch_cron_logs3.pl` documentation shows an example which indicates this regex and syntax should be valid:
```
<check>
<error>
*		Use of uninitialized value
*		(?<!Program caused arithmetic )Error
*		Warning
*               fatal
</error>
</check>
```
Ran the following Python script to verify the regex's are good. The unwanted lines with `error` or `warning` are not matched, while other `error` or `warning` lines are matched.
The text is adapted from an alert email today, with a couple of extra lines added.
```
import re
text = """
warning: could not open file!
WARNING: open_file(/proj/sot/ska3/flight/data/eng_archive/data/acis2eng/5min/1DEAMZT.h5, mode=a, filters=Filters(complevel=5, complib='zlib', shuffle=True, …
```

Add a negative lookahead assertion for log check

---

cheta/converters.py
cheta/tests/test_comps.py
cheta/update_archive.py

These are updates motivated by test warnings in our draft "speedy" Python 3.11 candidate environment.
Replace np.bool with bool (deprecated use of np.bool is an error in the speedy candidate).
```
(ska3-flight-2024.0rc7) jeanconn-fido> git rev-parse HEAD
55c4676df457f4b099c09234ebc1a86d60ee7eba
(ska3-flight-2024.0rc7) jeanconn-fido> pytest
========================================================== test session starts ==========================================================
platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.3.0
rootdir: /proj/sot/ska/jeanproj/git/cheta
plugins: timeout-2.2.0, anyio-4.2.0
collected 173 items                                                                                                                     
cheta/tests/test_comps.py …
```

Replace np.bool with bool

---

cheta/converters.py
cheta/fetch.py

Convert two remaining instances of `np.bool` to `bool`.
See: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. These deprecations are errors as of numpy 1.26. The code here is not covered in unit testing unfortunately.
None
Independent check of unit tests by [REVIEWER NAME]
No functional testing.

Convert remaining np.bool to bool

---

cheta/derived/comps.py
cheta/fetch.py
cheta/tests/test_comps.py
cheta/units.py

The `Computed_Quat` computed MSID is broken when there are actual bad data in the fetch range. The resultant `Msid` object has `vals` that are not filtered. This happens for samples at ['2024:064:09:27:02.652' '2024:064:09:27:03.677']. This problem has stopped updates to the Kalman watch perigee monitor window data page since around day 063.
The root cause of the problem was checking that a computed attribute (including `times`, `vals`, `bads`, `units`) is a subclass of `ndarray`. For the computed quaternion this is not the case, instead it is just follows (somewhat) the array protocol. For the purposes here I just check for a `shape` attribute.
This includes a change that was required by the new test. The goal was to show that no warnings are issued when fetching data over the impacted …

Fix computed Comp_Quat class and close pickle files

---

cheta/tests/test_intervals.py
cheta/tests/test_utils.py

This is a change intended for skare3 > 2025.0, where we will use astropy 7.0. It replaces uses of `Table.pformat_all()` wih `Table.pformat()`. This silences a warning.
```
(ska3-flight-2025.0rc5) ~/SAO/git/cheta pformat $ pytest cheta
============================================================= test session starts =============================================================
rootdir: /Users/javierg/SAO/git
configfile: pytest.ini
plugins: anyio-4.7.0, timeout-2.3.1
collected 174 items                                                                                                                           
cheta/tests/test_comps.py ............................................................ …
```

replace uses of pformat_all with pformat

---

cheta/fetch.py
cheta/tests/test_fetch.py
cheta/update_archive.py
cheta/update_client_archive.py
cheta/update_server_sync.py

This fixes cheta to support the CXOTIME_NOW environment variable and use it to mock the current time if defined.
The original code logic ignored that `DateTime(None)` returns the current time, so this PR fixes that.
- https://github.com/sot/chandra_time/pull/59
```
(ska3-flight-2025.0rc2) ➜  cheta git:(support-cxotime-now) git rev-parse --short HEAD
7488498
(ska3-flight-2025.0rc2) ➜  cheta git:(support-cxotime-now) pytest                    
=============================================== test session starts ================================================
rootdir: /Volumes/git
configfile: pytest.ini
plugins: doctestplus-1.3.0, anyio-4.7.0, timeout-2.3.1
collected 175 items …
```

Support CXOTIME_NOW environment variable

---

cheta/derived/comps.py
cheta/plot.py
cheta/remote_access.py
cheta/tests/test_remote_access.py

- Add a traceback output when there is an exception in remote access initialization. 
- Previously only the `str(exception)` was printed, which is generally not sufficient.
- Update remote access internal documentation to help in testing and diagnosing problems.
- Fix `MSID.iplot()`.
- This has been broken for a while, but it is still a useful function.
Not passing ruff but the issues are fixed in the follow-on #269 which merges into this PR.
```
(ska3-flight-2025.0rc2) ➜  cheta git:(remote-access-traceback) git rev-parse --short HEAD
3065bf7
(ska3-flight-2025.0rc2) ➜  cheta git:(remote-access-traceback) pytest
=============================================== test session starts ================================================ …
```

Add remote access traceback + fix MSID.iplot() + docs update

---

cheta/update_server_sync.py

After a 2-day shutdown of CXC processing, there was an exception in cheta_update_server_sync processing:
```
2025-01-30 04:42:13,408 Writing 3 row(s) to index file /proj/sot/ska3/flight/data/eng_archive/sync/sim_mrg/index.ecsv
2025-01-30 04:42:13,815 Writing /proj/sot/ska3/flight/data/eng_archive/sync/sim_mrg/2025-01-27T0256z/full.pkl.gz with 3948 rows of data and 36 msids
2025-01-30 04:42:14,496 Writing /proj/sot/ska3/flight/data/eng_archive/sync/sim_mrg/2025-01-27T0256z/5min.pkl.gz with 396 rows of data and 32 msids
2025-01-30 04:42:15,253 Writing /proj/sot/ska3/flight/data/eng_archive/sync/sim_mrg/2025-01-27T0256z/daily.pkl.gz with 4 rows of data and 32 msids
2025-01-30 04:42:15,428 Writing /proj/sot/ska3/flight/data/eng_archive/sync/sim_mrg/2025-01-28T1455z/full.pkl.gz with 3923 rows …
```

Require at least one row of data in full data for server sync

---

cheta/check_integrity.py
cheta/derived/__init__.py
cheta/get_telem.py
cheta/update_archive.py

Somehow a critical problem slipped through in #269 and two scripts used in daily updates of the cheta archive are broken. This was found in daily masters testing. This PR fixes them.
The `fetch.ENG_ARCHIVE` symbol is still not defined, but the two scripts now refer to the original `cheta.remote_access.ENG_ARCHIVE`.
In addition, I noticed a few lingering sphinx doc build warnings and fixed them.
None (given the change in #269).
```
(ska3-flight-2025.0rc2) ➜  cheta git:(fix-fetch-engarchive-break) git rev-parse --short HEAD
de25a1e
(ska3-flight-2025.0rc2) ➜  cheta git:(fix-fetch-engarchive-break) pytest
========================================== test session starts ===========================================
rootdir: /Volumes/git …
```

Fix update scripts broken in #269 + unrelated docs fixes

---

cheta/fetch.py

Fixes an issue where some code is relying on module attributes in `fetch_eng` that were removed in #269.
Adds back symbols to the public API that were removed.
```
(ska3-flight-2025.0rc2) ➜  cheta git:(add-back-all-exports) git rev-parse --short HEAD
e0432f3
(ska3-flight-2025.0rc2) ➜  cheta git:(add-back-all-exports) pytest
================================================ test session starts =================================================
rootdir: /Volumes/git
configfile: pytest.ini
plugins: hypothesis-6.125.2, doctestplus-1.3.0, anyio-4.7.0, timeout-2.3.1
collected 175 items                                                                                                  
cheta/tests/test_comps.py …
```

Add back most of fetch module contents to __all__
